version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    groups:
      react-router:
        patterns:
          - "@react-router/*"
          - "react-router*"
      vitest:
        patterns:
          - "vitest*"
          - "@vitest*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: "docker"
    directories:
      - /
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      cooldown:
        default-days: 3
      groups:
        actions:
          patterns:
            - "actions/*"
        docker:
          patterns:
            - "docker/*"
