// NOTE: This module is imported by `server.js`, which is run directly through
// `node` without Vite. Therefore, we need to make sure that the import paths
// can be resolved by Node.js (include file extension, do not rely on path
// aliases defined in `tsconfig.json`).

import pino from "pino";
import type { PrettyOptions } from "pino-pretty";
import { config } from "../config/config.ts";

const { LOG_LEVEL, ENVIRONMENT } = config();

export const logger = pino({
  level: LOG_LEVEL,
  errorKey: "error",
  serializers: {
    error: pino.stdSerializers.err,
    req: pino.stdSerializers.req,
    res: pino.stdSerializers.res,
  },
  redact: [
    // API request logs (`apiRequest()`)
    "headers.authorization",
    "headers.Authorization",
    "headers.cookie",
    "headers.Cookie",
    // Generated by request logs (pino-http)
    "req.headers.authorization",
    "req.headers.cookie",
    "res.headers.set-cookie",
  ],
  // Skip the pino-pretty worker-thread transport under Vitest (which sets
  // VITEST) — every test importing this module, directly or transitively,
  // would otherwise spawn one.
  transport:
    ENVIRONMENT === "development" && !process.env.VITEST
      ? {
          target: "pino-pretty",
          options: { colorize: true } satisfies PrettyOptions,
        }
      : undefined,
});
