// NOTE: This module is imported by `server.js`, which is run directly through
// `node` without Vite. Therefore, we need to make sure that the import paths
// can be resolved by Node.js (include file extension, do not rely on path
// aliases defined in `tsconfig.json`).

import pino from "pino";
import { config } from "../config/config.ts";

const { LOG_LEVEL, ENVIRONMENT } = config();

export const logger = pino(
  {
    level: LOG_LEVEL,
    errorKey: "error",
    serializers: {
      error: pino.stdSerializers.err,
      req: pino.stdSerializers.req,
      res: pino.stdSerializers.res,
    },
    redact: [
      // API request logs (`apiRequest()`)
      "headers.authorization",
      "headers.Authorization",
      "headers.cookie",
      "headers.Cookie",
      // Generated by request logs (pino-http)
      "req.headers.authorization",
      "req.headers.cookie",
      "res.headers.set-cookie",
    ],
  },
  ENVIRONMENT === "development" ? await prettyStream() : undefined,
);

async function prettyStream() {
  const pretty = await import("pino-pretty");
  return pretty.default({
    colorize: true,
    customPrettifiers: {
      req: (x) => {
        // The shape of `req` is guaranteed by pino-http.
        // oxlint-disable-next-line typescript/no-unsafe-type-assertion
        const req = x as { method: string; url: string };
        return `${req.method} ${req.url}`;
      },
      res: (x) => {
        // The shape of `res` is guaranteed by pino-http.
        // oxlint-disable-next-line typescript/no-unsafe-type-assertion
        const res = x as { statusCode: number };
        return `${res.statusCode}`;
      },
    },
  });
}
