export const ANSCHRIFTSTYP_CODE_PRIVATANSCHRIFT = "017";
export const STAAT_CODE_DEUTSCHLAND = "000";
export const TELEKOMMUNIKATIONSART_CODE_EMAIL = "001";
export const TELEKOMMUNIKATIONSART_CODE_MOBILTELEFON = "004";
export const ROLLENBEZEICHNUNG_CODE_PROZESSBEVOLLMAECHTIGTE = "132";
