const VERFAHREN_PAGE_LIMIT = 10;
const TOO_MANY_RESULTS_THRESHOLD = 50;
const MAX_EXACT_COUNT_DISPLAY = 100;

export {
  MAX_EXACT_COUNT_DISPLAY,
  TOO_MANY_RESULTS_THRESHOLD,
  VERFAHREN_PAGE_LIMIT,
};
