import { http, HttpResponse } from "msw";

import { getAllDokumenteByIds } from "./controllers/dokumente.js";
import {
  getAllEinreichungen,
  getEinreichungStatusByIds,
} from "./controllers/einreichung.js";
import { getGerichte } from "./controllers/gerichte.js";
import { getAuthTokens } from "./controllers/tokenExchange.js";
import {
  createVerfahren,
  filterVerfahrenByGericht,
  getAllVerfahren,
  getVerfahrenById,
  paginateVerfahren,
  searchVerfahren,
  sortVerfahren,
} from "./controllers/verfahren.js";

/**
 * All defined Handlers intercept a request and handle its response
 *
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 *
 * @see https://mswjs.io/docs/concepts/request-handler
 * @see https://mswjs.io/docs/basics/intercepting-requests
 * @see https://mswjs.io/docs/basics/mocking-responses
 */

// KOMPLA_API_URL
const mockKomplaApiUrl = "https://app.kompla-justiz.sinc.de";
// KOMPLA_IDP_ISSUER
const mockKomplaIdpIssuer = "https://login.kompla-justiz.sinc.de";

export const handlers = [
  // Verfahren
  http.get(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren`,
    async ({ request }) => {
      const url = new URL(request.url);
      const offsetParam = url.searchParams.get("offset");
      const limitParam = url.searchParams.get("limit");
      const gerichtParam = url.searchParams.get("gericht");
      const sortParam = url.searchParams.get("sort");
      const searchParam = url.searchParams.get("search_text");

      let filteredVerfahren = getAllVerfahren();

      if (gerichtParam) {
        filteredVerfahren = filterVerfahrenByGericht(
          filteredVerfahren,
          gerichtParam,
        );
      }

      if (searchParam) {
        filteredVerfahren = searchVerfahren(filteredVerfahren, searchParam);
      }

      if (sortParam) {
        filteredVerfahren = sortVerfahren(filteredVerfahren, sortParam);
      }

      const paginatedVerfahren = paginateVerfahren(
        filteredVerfahren,
        offsetParam,
        limitParam,
      );

      const getVerfahrenResponse = [paginatedVerfahren, { status: 200 }];
      return HttpResponse.json(...getVerfahrenResponse);
    },
  ),

  http.get(`${mockKomplaApiUrl}/:environment/api/v1/gerichte`, async () => {
    const gerichteResponse = [getGerichte(), { status: 200 }];
    return HttpResponse.json(...gerichteResponse);
  }),

  // endpoint is not used by the frontend at the moment
  http.get(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren/:verfahrenId`,
    async ({ params }) => {
      const requestedVerfahren = getVerfahrenById(params.verfahrenId);

      console.log("Requested verfahren:", requestedVerfahren);

      const resultArray = [requestedVerfahren, { status: 200 }];

      return HttpResponse.json(...resultArray);
    },
  ),

  // Create Verfahren
  http.post(`${mockKomplaApiUrl}/:environment/api/v1/verfahren`, () => {
    const newVerfahren = createVerfahren();
    // API returns array (known bug)
    return HttpResponse.json([newVerfahren], { status: 201 });
  }),

  // Create Einreichung
  http.post(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren/:verfahrenId/einreichungen`,
    ({ params }) => {
      const id = crypto.randomUUID();
      const newEinreichung = {
        id: id,
        verfahren_id: params.verfahrenId,
        status: "ENTWURF",
        erstellt_am: new Date().toISOString(),
        erstellt_von: "",
      };
      console.log("POST einreichung with id", id);
      return HttpResponse.json(newEinreichung, { status: 201 });
    },
  ),

  // Upload Dokument
  http.post(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren/:verfahrenId/einreichungen/:einreichungId/dokumente`,
    ({ params }) => {
      const newDokument = {
        id: crypto.randomUUID(),
        einreichung_id: params.einreichungId,
        status: "ERSTELLT",
        name: "sample_klaver_3500001.xml",
        size_in_bytes: 3481,
        type: "XJUSTIZ",
        gesendet_am: null,
        eingereicht_am: null,
        erstellt_von: "",
        erstellt_am: new Date().toISOString(),
      };
      console.log("POST dokumente with {einreichung-id}", params.einreichungId);
      return HttpResponse.json([newDokument], { status: 201 });
    },
  ),

  // Get Einreichungen for a Verfahren
  http.get(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren/:verfahrenId/einreichungen`,
    () => {
      const requestedEinreichungen = getAllEinreichungen();

      console.log("Requested einreichungen:", requestedEinreichungen);

      const resultArray = [requestedEinreichungen, { status: 200 }];

      return HttpResponse.json(...resultArray);
    },
  ),

  // Get the status of a specfic Einreichung for a Verfahren
  http.get(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren/:verfahrenId/einreichungen/:einreichungId/validierungsstatus`,
    async ({ params }) => {
      const requestedEinreichungStatus = getEinreichungStatusByIds(
        params.verfahrenId,
        params.einreichungId,
      );

      console.log(
        "Requested validierungsstatus for einreichung:",
        requestedEinreichungStatus,
      );

      const resultArray = [requestedEinreichungStatus, { status: 200 }];

      return HttpResponse.json(...resultArray);
    },
  ),

  // Get all dokumente of a specfic Einreichung for a Verfahren
  http.get(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren/:verfahrenId/einreichungen/:einreichungId/dokumente`,
    async ({ params }) => {
      const requestedDokumenteForEinreichung = getAllDokumenteByIds(
        params.verfahrenId,
        params.einreichungId,
      );

      console.log(
        "Requested all dokumente for einreichung:",
        requestedDokumenteForEinreichung,
      );

      const resultArray = [requestedDokumenteForEinreichung, { status: 200 }];

      return HttpResponse.json(...resultArray);
    },
  ),

  // KomPla IdP Token Exchange
  http.post(
    `${mockKomplaIdpIssuer}/realms/:environment/protocol/openid-connect/token`,
    () => {
      const post200Response = [getAuthTokens(), { status: 200 }];
      return HttpResponse.json(...post200Response);
    },
  ),
];
