import { http, HttpResponse } from "msw";

import { gerichte } from "./data/gerichte.js";
import { mockKomPlaIdPTokenExchange } from "./data/tokenExchange.js";
import { verfahrenMockData } from "./data/verfahren.js";

/**
 * All defined Handlers intercept a request and handle its response
 *
 * This file was initially AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 *
 * @see https://mswjs.io/docs/concepts/request-handler
 * @see https://mswjs.io/docs/basics/intercepting-requests
 * @see https://mswjs.io/docs/basics/mocking-responses
 */

// KOMPLA_API_URL
const mockKomplaApiUrl = "https://app.kompla-justiz.sinc.de";
// KOMPLA_IDP_ISSUER
const mockKomplaIdpIssuer = "https://login.kompla-justiz.sinc.de";

export const handlers = [
  // Verfahren
  http.get(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren`,
    async ({ request }) => {
      const url = new URL(request.url);
      const offsetParam = url.searchParams.get("offset");
      const limitParam = url.searchParams.get("limit");
      const gerichtParam = url.searchParams.get("gericht");
      const sortParam = url.searchParams.get("sort");
      const searchParam = url.searchParams.get("search_text");

      console.log("URL Sort Param:", sortParam);
      console.log("URL Search Params:", url.searchParams.toString());

      let filteredVerfahren = verfahrenMockData;

      if (gerichtParam) {
        filteredVerfahren = filteredVerfahren.filter(
          (verfahren) => verfahren.gericht.id === gerichtParam,
        );
      }

      if (searchParam) {
        const matchesString = (val) =>
          typeof val === "string" &&
          val.toLowerCase().includes(searchParam.toLowerCase());

        filteredVerfahren = filteredVerfahren.filter((verfahren) => {
          // Top-level string fields
          if (
            matchesString(verfahren.aktenzeichen_gericht) ||
            matchesString(verfahren.gericht?.wert) ||
            matchesString(verfahren.gericht?.id)
          ) {
            return true;
          }

          // Beteiligungen and nested fields
          return verfahren.beteiligungen?.some((b) => {
            // Beteiligung itself
            if (matchesString(b.name) || matchesString(b.id)) return true;

            // Rollen
            if (b.rollen?.some((r) => matchesString(r.id))) return true;

            // Prozessbevollmaechtigte
            return b.prozessbevollmaechtigte?.some((p) => {
              const bev = p.bevollmaechtigter;
              return (
                matchesString(p.aktenzeichen) ||
                matchesString(bev?.id) ||
                matchesString(bev?.safe_id) ||
                matchesString(bev?.name)
              );
            });
          });
        });
      }

      if (sortParam) {
        const isDescending = sortParam.startsWith("-");
        const sortField = isDescending ? sortParam.slice(1) : sortParam;

        filteredVerfahren.sort((a, b) => {
          if (a[sortField] < b[sortField]) return isDescending ? 1 : -1;
          if (a[sortField] > b[sortField]) return isDescending ? -1 : 1;
          return 0;
        });
      }

      const total = filteredVerfahren.length;

      const offsetNum = offsetParam ? Number.parseInt(offsetParam, 10) || 0 : 0;
      const limitNum = limitParam
        ? Number.parseInt(limitParam, 10) || total
        : total;

      console.log("Received params:", url.searchParams.toString());
      console.log(
        "Fetching verfahren with offset:",
        offsetNum,
        "and limit:",
        limitNum,
        "gericht:",
        gerichtParam,
      );

      const paged = filteredVerfahren.slice(offsetNum, offsetNum + limitNum);

      const getVerfahrenResponse = [paged, { status: 200 }];
      return HttpResponse.json(...getVerfahrenResponse);
    },
  ),

  http.get(`${mockKomplaApiUrl}/:environment/api/v1/gerichte`, async () => {
    const gerichteResponse = [gerichte, { status: 200 }];
    return HttpResponse.json(...gerichteResponse);
  }),

  // endpoint is not used by the frontend at the moment
  http.get(
    `${mockKomplaApiUrl}/:environment/api/v1/verfahren/:verfahrenId`,
    async ({ params }) => {
      const requestedVerfahren = verfahrenMockData.find(
        (item) => item.id === params.verfahrenId,
      );

      console.log("Requested verfahren:", requestedVerfahren);

      const resultArray = [requestedVerfahren, { status: 200 }];

      return HttpResponse.json(...resultArray);
    },
  ),

  // KomPla IdP Token Exchange
  http.post(
    `${mockKomplaIdpIssuer}/realms/:environment/protocol/openid-connect/token`,
    () => {
      const post200Response = [mockKomPlaIdPTokenExchange, { status: 200 }];
      return HttpResponse.json(...post200Response);
    },
  ),
];
