name: Scan

on:
  schedule:
    - cron: "0 6 * * *" # Every day at 8am
  # Allow to run this workflow manually
  workflow_dispatch:
  workflow_call:

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_IMAGE_NAME: ${{ github.repository }}
  # Use 'latest' for main, commit hash for PR or other branches
  CONTAINER_IMAGE_VERSION: ${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # trivy scan needs this
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Restore Docker image cache
        uses: actions/cache@v4
        with:
          path: |
            /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}

      - name: Load cached Docker image
        id: load-docker-image
        run: |
          IMAGE_PATH="/tmp/.docker-cache/${{ env.CONTAINER_IMAGE_NAME }}_${{ github.sha }}.tar"

          if docker load -i $IMAGE_PATH; then
            echo "docker-image-load-successful=true" >> $GITHUB_OUTPUT
            echo "Docker image loaded from cache: $IMAGE_PATH"
          else
            echo "docker-image-load-successful=false" >> $GITHUB_OUTPUT
            echo "Docker image not found in cache: $IMAGE_PATH"
          fi

      - name: Validate github workflow files to have pinned versions
        uses: digitalservicebund/github-actions-linter@7cb107efafe7cb97a58e685a08a1014744b89f71 # v0.1.11

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          # Specify multiple registries: try default GitHub registry, if too many requests, use the aws mirror.
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          image-ref: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE_NAME }}:${{ env.CONTAINER_IMAGE_VERSION }}
          format: "sarif"
          # By default SARIF format enforces output of all vulnerabilities regardless of configured severities.
          # To override this set limit-severities-for-sarif to true.
          limit-severities-for-sarif: true
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Check trivy results
        run: |
          if grep -qE 'HIGH|CRITICAL' trivy-results.sarif; then
            echo "Vulnerabilities found:"

            jq -r '
              .runs[].results[] |
              "Rule ID: \(.ruleId)\n" +
              "Package: \(.message.text | split("\n")[0] | ltrimstr("Package: "))\n" +
              "Installed Version: \(.message.text | split("\n")[1] | ltrimstr("Installed Version: "))\n" +
              "Severity: \(.message.text | split("\n")[2] | ltrimstr("Severity: "))\n" +
              "\(.message.text | split("\n")[4] | ltrimstr("Link: "))\n"
            ' trivy-results.sarif
            # Exit with error status
            exit 1
          else
            echo "No significant vulnerabilities found"
            exit 0
          fi

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@f443b600d91635bebf5b0d9ebc620189c0d6fba5 # v3.29.5
        if: always() # Bypass non-zero exit code..
        with:
          sarif_file: "trivy-results.sarif"

      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf # v1.5.0
        if: ${{ failure() }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
